In [18]:
import numpy as np, numpy.random

n_portfolio = 100
n_asset = 3

# generate random matrix
rand_matrix = np.random.random((n_portfolio, n_asset))
rand_matrix

array([[ 0.91601036,  0.53874316,  0.5586627 ],
       [ 0.10008792,  0.11735098,  0.67045941],
       [ 0.38255357,  0.40876397,  0.08970003],
       [ 0.43613111,  0.08255963,  0.7611353 ],
       [ 0.15521143,  0.0387504 ,  0.05267705],
       [ 0.60063718,  0.04208579,  0.63247445],
       [ 0.65293382,  0.60177455,  0.29522739],
       [ 0.26816122,  0.31024405,  0.26679297],
       [ 0.85765749,  0.77974141,  0.29518313],
       [ 0.68791262,  0.84689031,  0.05957845],
       [ 0.07821884,  0.34377785,  0.05276095],
       [ 0.07228537,  0.88739924,  0.99302615],
       [ 0.06269996,  0.46132722,  0.53619575],
       [ 0.01760579,  0.18091787,  0.90616046],
       [ 0.87995517,  0.86492115,  0.49367793],
       [ 0.0273386 ,  0.57658775,  0.96336691],
       [ 0.38726069,  0.64105052,  0.20095051],
       [ 0.88128828,  0.03476843,  0.86927836],
       [ 0.25404659,  0.71936492,  0.15426431],
       [ 0.50621632,  0.39632506,  0.34123452],
       [ 0.72235809,  0.88374393,  0.111

In [23]:
# create 100 portfolios
portfolio = np.zeros((n_portfolio, n_asset))
i = 0
for row in rand_matrix:
    row_sum = np.sum(row)
    j = 0
    for col in row:
        portfolio[i][j] = col/row_sum
        j += 1
    i += 1
print portfolio

[[ 0.4549533   0.26757665  0.27747005]
 [ 0.11272453  0.13216714  0.75510832]
 [ 0.43421787  0.46396801  0.10181412]
 [ 0.34077374  0.06450848  0.59471778]
 [ 0.62930643  0.15711391  0.21357967]
 [ 0.47101505  0.03300335  0.4959816 ]
 [ 0.42126508  0.38825774  0.19047718]
 [ 0.31727612  0.36706661  0.31565727]
 [ 0.4437884   0.40347131  0.15274028]
 [ 0.43146052  0.53117173  0.03736775]
 [ 0.16475531  0.7241123   0.11113238]
 [ 0.03701796  0.45444479  0.50853725]
 [ 0.05913847  0.43512285  0.50573868]
 [ 0.0159374   0.1637734   0.8202892 ]
 [ 0.39309084  0.38637489  0.22053427]
 [ 0.01744319  0.36788759  0.61466921]
 [ 0.31503518  0.5214923   0.16347252]
 [ 0.49362626  0.01947446  0.48689928]
 [ 0.22528335  0.63791819  0.13679845]
 [ 0.40699962  0.31864668  0.2743537 ]
 [ 0.42063604  0.51461255  0.06475141]
 [ 0.85610562  0.10128799  0.04260639]
 [ 0.15957732  0.51231251  0.32811018]
 [ 0.13797076  0.22724169  0.63478755]
 [ 0.06848858  0.3082472   0.62326423]
 [ 0.37461086  0.33984803

In [29]:
assets = [0.1, 0.2, 0.15]
# find expected return of each portfolio
E = np.dot(portfolio, assets)
print E

[ 0.14063117  0.15097213  0.15148751  0.13618674  0.12639037  0.12809942
  0.14834963  0.15248952  0.14798415  0.15498556  0.17796785  0.17087134
  0.16879922  0.1573918   0.1496642   0.16752222  0.16032286  0.12629241
  0.17063174  0.14558235  0.15469883  0.11225912  0.16763676  0.15446355
  0.16198793  0.14826186  0.1362823   0.18449888  0.11934322  0.16610175
  0.16467669  0.15190839  0.15104157  0.16503989  0.15634504  0.18956114
  0.15389853  0.15074356  0.1530711   0.14968122  0.14260015  0.13575156
  0.1763406   0.15163359  0.15551649  0.14405092  0.16919931  0.16750792
  0.12306184  0.15199381  0.18146762  0.16867045  0.16884584  0.14995778
  0.1236781   0.15076209  0.13648722  0.16455656  0.12729911  0.1421088
  0.12888173  0.11830937  0.12657815  0.15370103  0.14072212  0.1328907
  0.13268522  0.14716592  0.15055757  0.14384466  0.1687054   0.12374708
  0.14460179  0.14331685  0.14589542  0.15062581  0.15327102  0.14062629
  0.14349503  0.17307444  0.15402311  0.12879224  0.1

In [31]:
# covariance
C = [[0.005 -0.01 0.004]
     [-0.01 0.04 -0.002]
     [0.004 -0.002 0.023]]
print C

SyntaxError: invalid syntax (<ipython-input-31-4060ad034a47>, line 2)